### ISSUE TITLE
Can't save attachments

### ISSUE THREAD

**Issue by simeoreig** [Offerel/roundcube_storage#10]
All is workig as expected: I can open files, attach files from stored, upload them etcetera but I can't save attachments, this is the error log:

`[23-May-2020 23:39:53 Europe/Rome] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function storage::save_one(), 0 passed in /usr/local/www/roundcube/program/lib/Roundcube/rcube_plugin_api.php on line 494 and exactly 1 expected in /usr/local/www/roundcube/plugins/storage/storage.php:65
Stack trace:
#0 /usr/local/www/roundcube/program/lib/Roundcube/rcube_plugin_api.php(494): storage->save_one()
#1 /usr/local/www/roundcube/index.php(294): rcube_plugin_api->exec_action('storage.save_on...')
#2 {main}
  thrown in /usr/local/www/roundcube/plugins/storage/storage.php on line 65
`

roundcube 1.4.2 

Thanks for your time and this fantastic plugin

**Comment by Offerel** [comment]
Hmm must be something with newer RC versions. I will have a look into this in the next days.

**Comment by Offerel** [comment]
It seems, i have found a quick fix. Have uploaded it in the dev branc. I will make a new release with a newer elfinder release in the next days.

**Comment by simeoreig** [comment]
It works perfectly!. Looking forward the new version with elfinder updated.
Many many thanks again for your work and time
