### ISSUE TITLE
Button to attach file when composing doesn't appear

### ISSUE THREAD

**Issue by aalcaine** [Offerel/roundcube_storage#5]
When composing a new message, no button appears to attach from Storage:

![composing_01](https://user-images.githubusercontent.com/32023824/37387087-65b40966-275b-11e8-9428-90d9827169f4.png)

When I click the "standard" button "Adjunta un fitxer" (Attach a file) appears a javascript dialog and a browser file selector:

![composing_02](https://user-images.githubusercontent.com/32023824/37387119-84f49fe8-275b-11e8-8b45-966cf64bc550.png)

If I cancel/close the browser file selector I can see the javascript dialog, but this allows only to select again using the file browser:

![composing_03](https://user-images.githubusercontent.com/32023824/37387138-9775b6f2-275b-11e8-84be-0f59ec470e05.png)

... seems that the "anchor" to select a file from Storage doesn't match?

Nothing appears in the log nor in the JS console.

**Comment by aalcaine** [comment]
If I understand it well, the hint about the maximum allowed filesize appears (at least with this version of RoundCube, 1.2.7) below the "Browse" button and above the "Add" and "Cancel" buttons in the javascript dialog:

![max_upload_size](https://user-images.githubusercontent.com/32023824/37389585-33012e0e-2765-11e8-9ab2-a6ecc323a5ce.png)

The source for the javascript dialog is:

```
<div id="upload-dialog" class="propform popupdialog ui-dialog-content ui-widget-content" aria-hidden="true" style="display: block; width: auto; min-height: 78px; max-height: none; height: auto;">
	<h2 id="aria-label-uploaddialog" class="voice">Formulari per pujar adjunts</h2>
	<div id="uploadform"><form id="uploadformFrm" name="uploadform" method="post" enctype="multipart/form-data" action="./?_task=mail">
<input name="_token" value="mHqwyItUKxqAV1v0D6JcyavaQ2Ves66R" type="hidden"><div><input name="_attachments[]" multiple="multiple" type="file"><a class="iconlink add" href="#add">Add</a></div>
<div class="hint">La mida màxima permesa del fitxer és 32 MB</div>
</form>
</div>

	<div class="formbuttons">
		<input class="button mainaction" id="rcmbtn127" onclick="return rcmail.command('send-attachment','',this,event)" value="Afegeix" type="button">
		<input class="button" onclick="UI.show_uploadform()" id="rcmbtn128" value="Cancel·la" type="button">
	</div>
</div>

```

What I don't know is WHERE should it appear the "Attach from Server" button.

1. Using skin LARRY

In the compose screen appears one button with the text "Attach a file" and a dropzone below. 

![captura de pantalla 2018-03-14 a les 8 57 40](https://user-images.githubusercontent.com/32023824/37389779-e4699118-2765-11e8-9dac-d799cbb99f67.png)

Clicking on that button does the same as clicking the "Attach" button in the toolbox:

![captura de pantalla 2018-03-14 a les 8 58 50](https://user-images.githubusercontent.com/32023824/37389793-efe61dcc-2765-11e8-8460-ae3da062f4e8.png)

2. Using skin CLASSIC

In the compose screens YES, appears next to the " + " sign that shows the same javascript dialog + browser file selection a small button that YES, allows you to select a file from server:

![captura de pantalla 2018-03-14 a les 8 59 36](https://user-images.githubusercontent.com/32023824/37389851-292cd062-2766-11e8-9998-b7a49d3e015e.png)

Clicking the "Open from server" button shows a dialog working well:

![captura de pantalla 2018-03-14 a les 9 01 02](https://user-images.githubusercontent.com/32023824/37389887-4a7a4146-2766-11e8-8bdb-9bc3fd1d60a4.png)

Clicking the "Attach" button from the toolbar does the same as clicking the " + " button:

![captura de pantalla 2018-03-14 a les 9 02 14](https://user-images.githubusercontent.com/32023824/37389920-679fa612-2766-11e8-9a75-8c47ffb54123.png)

Appears the javascript dialog in the background and the browser file selection in the front. Until I don't close the file browser selection file I cannot interact with the javascript dialog.

The javascript dialog allows only to select files (again) from the browser file dialog.

**Comment by aalcaine** [comment]
The source code for the "Adjunta un fitxer" (Attach a file) from the compose window (not the javascript dialog) which appears below the "drop file zone" is:

```
<div id="composeview-bottom">
	<div id="composebodycontainer">
		<label for="composebody" class="voice">Cos del missatge</label>
		<input type="hidden" name="_draft_saveid"><input type="hidden" name="_draft" value="yes"><input type="hidden" name="_is_html" value="0"><input type="hidden" name="_framed" value="1"><textarea name="_message" id="composebody" cols="70" rows="20" tabindex="1"></textarea>
<iframe name="savetarget" src="program/resources/blank.gif" style="width:0;height:0;border:none;visibility:hidden;" aria-hidden="true"></iframe>
	</div>
	<div id="compose-attachments" class="rightcol" role="region" aria-labelledby="aria-label-composeattachments">
		<h2 id="aria-label-composeattachments" class="voice">Adjunts</h2>
		<div style="text-align:center; margin-bottom:20px">
			<input type="button" class="button" onclick="UI.show_uploadform(event);return false" tabindex="1" id="rcmbtn123" value="Adjunta un fitxer">
		</div>
		<ul id="attachment-list" class="attachmentslist" data-tabindex="1">
</ul>

		
	</div>
<!--
	<div id="composeformbuttons" class="footerleft formbuttons floating">
		<input type="button" class="button mainaction" tabindex="11" id="rcmbtn124" onclick="return rcmail.command('send','',this,event)" value="Envia el missatge" disabled="disabled">
		<input type="button" class="button" tabindex="12" id="rcmbtn125" onclick="return rcmail.command('savedraft','',this,event)" value="Desa com a esborrany" disabled="disabled">
		<input type="button" class="button" tabindex="13" id="rcmbtn126" onclick="return rcmail.command('list','',this,event)" value="Cancel·la" disabled="disabled">
	</div>
-->
</div>
```

And the source code for the button "Attach" from the toolbar is (just in case you need it):

`<a class="button attach" title="Adjunta un fitxer" onclick="UI.show_uploadform(event);return false" aria-haspopup="true" aria-expanded="false" tabindex="2" id="rcmbtn111" role="button" href="#">Adjunta</a>`

**Comment by Offerel** [comment]
OK. Maybe this has changed in the current Roundcube version. Im using version 1.3.4 and at least with larry, the button appears in the mail compose window:
![hc_004](https://user-images.githubusercontent.com/14041522/37390770-73267f6c-2769-11e8-9449-8ca3dbf1c46b.jpg)
The JQuery searches only in this compose window for `<a class=button`, and add's afterwards the new button. In your case, i fear there is only a `<input class=button>` instead of `<a class=button>`. I don't know if this was changed in some release, i can only assume this.

I don't want to backport the plugin currently, without to know, if this works for your issue. But maybe you can change line 11 in client.js from

`var fbutton = $("#compose-attachments").contents().find("a.button"); `
to 
`var fbutton = $("#compose-attachments").contents().find(".button"); `

clear the browser cache and report, if this works. Alternatively you can update to the latest version of Roundcube.

**Comment by aalcaine** [comment]
Hi, **YES**, changing the attribute works well:

![captura de pantalla 2018-03-14 a les 9 58 48](https://user-images.githubusercontent.com/32023824/37392414-6129c4f4-276e-11e8-9964-f59469399b9f.png)

If you prefer, wait for more changes you might have to do to update the package, for me it's ok now and I'll update the plugin when you release a new branch.

**Comment by Offerel** [comment]
many thx for reporting. I have added the change in my local repo, but commit it when there are more and i close the issue.

Have a nice day.
