### ISSUE TITLE
Screen too short?

### ISSUE THREAD

**Issue by bastiaan2003** [Offerel/roundcube_storage#7]
UPDATE: This is only with the Classic template!

My screen is too short. If I open the contextmenu, I only see half of the options.
The same goes for opening a preview of a file. I can only see two or three lines.

![short_screen](https://user-images.githubusercontent.com/36445995/56658000-c3a65c80-6699-11e9-928b-b101cf46a0fd.png)

**Comment by Offerel** [comment]
What for browser are you using? Are there other AddOns active?

**Comment by bastiaan2003** [comment]
I used Internet Explorer (an old one) and Firefox (the latest version)
But again, this only happens with the classic template.

**Comment by Offerel** [comment]
I cant test Internet Explorer, because i didn't have access to a old Windows PC. I is ages ago, that i have used Windows. But i test it with Firefox and fix it, if i found something.
